### ISSUE TITLE
Tooltip not show on commit button when it is disabled

### ISSUE THREAD

**Issue by andrewhli** [jupyterlab/jupyterlab-git#1035]
Hi, 

Here are my steps so far:

1. Created private GitHub SSH key in ~/.ssh (e.g. ~/.ssh/id_x)
2. Cloned remote GitHub repo via Jupyterlab Git UI (sidebar), using the SSH URL (e.g. git@github.com:user/repo.git)
3. Edited the readme in the repo via Jupyterlab
4. Tried to commit, but the option is greyed out. There are console warnings but no errors.
5. Updated - according to krassowski: files need to be added to "Staged" to enable commits. "Maybe there should be a tooltip showing up when hovering over the greyed out "Commit" button saying "Add at least one file to the staging area to commit"?"

![Screen Shot 2021-09-14 at 12 22 46 PM](https://user-images.githubusercontent.com/5068143/133304709-b9035460-2571-4c76-be85-01756374ed7e.png)

Would appreciate any help on this. Thanks!

**Comment by krassowski** [comment]
Welcome! You need to add a file to the staging area so that the extension knows which is supposed to be committed. You can do this by hovering over the entries on the "Changed" or "Untracked" list (depending on what you would like to add) which should make a plus (+) icon appear - click on it to add a file and you will be able to commit. Alternatively, use context menu in the file browser  (Git submenu).

**Comment by andrewhli** [comment]
Thanks! Adding the files to "Staged" worked perfectly. Any interest to adding this step to the jupyterlab-git Readme? I've been so used to using GitHub desktop, where it only shows the changes and skips over the "Staged" step (not visible to users like me), so I didn't know this was a required step in jupyterlab-git

**Comment by krassowski** [comment]
You may like the `simpleStaging` option (see https://github.com/jupyterlab/jupyterlab-git#ui-settings). This step is not surprising to most Git users, but I see how the GUI is not helping currently.

Maybe there should be a tooltip showing up when hovering over the greyed out "Commit" button saying "Add at least one file to the staging area to commit"?

**Comment by andrewhli** [comment]
The tooltip makes sense. I'll change this into a feature request and rename the title

**Comment by fcollonval** [comment]
Just a note when tackling this: 

- An appropriated title is already set to the button
- It is not displayed due to the style `pointer-events: none;` set by material-ui:

![image](https://user-images.githubusercontent.com/8435071/133386196-4557457d-6fa3-44ae-a929-b2d466e31ac9.png)

@andrewhli would like to make a PR to correct this one?

You need to add:

```css
pointer-events: auto !important;
```

in the css rules:

https://github.com/jupyterlab/jupyterlab-git/blob/4623fae42767ff41f309225f088fcfa6edea9ae3/src/style/CommitBox.ts#L109

**Comment by fcollonval** [comment]
Fixed by #1036
