### ISSUE TITLE
Unable to view full Git History of relocated files

### ISSUE THREAD

**Issue by willyyang** [jupyterlab/jupyterlab-git#1038]
## Description

Unable to view full Git History of files that have been relocated

## Reproduce
```
## in demo root repo

# add to file
echo "this is a test" > test.txt
git add test.txt
git commit -m  'add test.txt to root'

# update file 
echo "this is another test" >> test.txt
git add test.txt
git commit -m 'append more to test.txt'

# move file
mkdir -p another_folder
mv test.txt another_folder/test.txt
git add test.txt
git add another_folder/test.txt
git commit -m 'move test.txt to another_folder/test.txt'

git push
```

After the above setup, go into the UI, show history on `another_folder/test.txt` and the first 2 commits will not show the text that has been added and the text that has been appended. Only the last commit will show the diff consisting
```
this is a test
this is another test
```

## Expected behavior

The expected behavior would be the Git History consists of text changes from the first commit and second commit and a mv file in the third commit. 

## Context

```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"

# pip list | grep jupyterlab-git
jupyterlab-git         0.32.3

# jupyter labextension list
JupyterLab v3.0.17
  @jupyterlab/git v0.32.3 enabled OK (python, jupyterlab-git)

# jupyter server extension list
  jupyterlab_git enabled
  - Validating jupyterlab_git...
     jupyterlab_git 0.32.3 OK

# git --version
git version 2.20.1
```

**Comment by willyyang** [comment]
@navn-r

**Comment by navn-r** [comment]
Hey @willyyang, I followed the exact same steps (just copied and pasted) that you did, and this is the output I get when:

1. Clicking into `another_folder`
2. Right-clicking `test.txt` and viewing history

![image](https://user-images.githubusercontent.com/59669957/133688764-e38f486c-b6d4-4a46-bca7-4f0aaa98ff27.png)

Internally we call this command to get the single file history:
```sh
git log --pretty=format:%H%n%an%n%ar%n%s --numstat --follow -- another_folder/test.txt
```

Key thing to note is the `--follow`  option, as its purpose is to show rename/relocated file commits ([source](https://stackoverflow.com/questions/5743739/how-to-really-show-logs-of-renamed-files-with-git))

Are you missing any other steps you have done in your **Reproduce** section?

**Comment by willyyang** [comment]
hey @navn-r , this part you're showing with the commit message and sha is fine. It's the right hand side that's showing the diffs that I'm concerned about. 
When you click on your `d19001d`, the right hand side will show there's no diff. same with `263f762`.  The following will show in the `e6d4eed` change, where this should have been incrementally shown (via diffs) from the other 2 prior changes. 

```
this is a test
this is another test
```

**Comment by navn-r** [comment]
Oh, apologies for the confusion, but I get what you mean now. Thanks for finding this @willyyang 

![image](https://user-images.githubusercontent.com/59669957/133697238-14543127-ae5c-48a5-8fe5-523a2a9d4d31.png)

Yea this is a bug, and the diff from clicking a single file commit, should be the same as clicking the file from the entire repository commit. 

From what I've found, it seems that this is happening because when you click on the single file commit, the filename path sent to git api is `another_file/test.txt`, but in the repository commit its strictly sent as `test.txt`. SHA is the same for both which makes sense.

So we need to find a way to chop off `another_file` when trying to get the diff of a commit that was made *before the relocation commit*, while also trying not to break just regular files nested in subdirectories. 

Any suggestions? @fcollonval

**Comment by fcollonval** [comment]
Hey, this is a complex problem because it requires knowing the name of the file in a specific commit to be able to get the content. If the renaming happens in the same directory, I pretty sure the result will be the same.

**Comment by fcollonval** [comment]
I tested a bit options of the log command.

To sum up, the current behavior is:

```bash
$ git log --pretty=format:%H%n%an%n%ar%n%s -n3 --numstat --follow -- src/main.ts
2932510dda42a58619a4ccfdce8ce65700599705
Frédéric Collonval
37 minutes ago
rename index.ts
0       0       src/{index.ts => main.ts}

8f2b16d8f0aff9b99f07f827d1e57a9ef6a14b2e
Navinn Ravindaran
3 weeks ago
Remove template from DiffModel
1       1       src/index.ts

26a47573531d44efeb039912e535287b57725981
Frédéric Collonval
4 weeks ago
`jupyterlab-git` incorrectly responds to filebowser events of other extensions Fixes #1014
14      23      src/index.ts
```

We need to send back the file name that is listed. The trouble is the syntax for rename that makes it hard to get the two paths. So we should switch to use `\x00` delimiter instead of `\n`:

```bash
$git log --pretty=format:%H%n%an%n%ar%n%s -z -n3 --numstat --follow -- src/main.ts
2932510dda42a58619a4ccfdce8ce65700599705
Frédéric Collonval
50 minutes ago
rename index.ts
0       0       ^@src/index.ts^@src/main.ts^@^@8f2b16d8f0aff9b99f07f827d1e57a9ef6a14b2e
Navinn Ravindaran
3 weeks ago
Remove template from DiffModel
1       1       src/index.ts^@^@26a47573531d44efeb039912e535287b57725981
Frédéric Collonval
4 weeks ago
`jupyterlab-git` incorrectly responds to filebowser events of other extensions Fixes #1014
14      23      src/index.ts^@
```

Or even more `\x00`

```bash
$ git log --pretty=format:%H%x00%an%x00%ar%x00%s%x00 -z -n3 --numstat --follow -- src/main.ts
2932510dda42a58619a4ccfdce8ce65700599705^@Frédéric Collonval^@38 minutes ago^@rename index.ts^@
0       0       ^@src/index.ts^@src/main.ts^@^@8f2b16d8f0aff9b99f07f827d1e57a9ef6a14b2e^@Navinn Ravindaran^@3 weeks ago^@Remove template from DiffModel^@
1       1       src/index.ts^@^@26a47573531d44efeb039912e535287b57725981^@Frédéric Collonval^@4 weeks ago^@`jupyterlab-git` incorrectly responds to filebowser events of other extensions Fixes #1014^@
14      23      src/index.ts^@
```

> Note that two log items are separated by a two `\x00` characters but that the line separator is kept before printing the `numstat` info.

Would like to tackle this one @navn-r ?

**Comment by navn-r** [comment]
Thanks for the explanation @fcollonval, I can take this one.

Question; For the rename commit, when we want to show the diff, are we still gonna use the renamed commit filename (`src/main.ts` from your example) only? Or should we do something like how VSCode does it, where left side is the old filename, and right side is the new filename?

![image](https://user-images.githubusercontent.com/59669957/133783929-ed8d3b12-8a9e-45a0-93f2-f686ec9b1d32.png)


For the second option, we'd probably have to change the `gitFileDiff` execute, to have the challenger and reference be two separate filenames. Rather than the single filename given from `filePath` [here](https://github.com/jupyterlab/jupyterlab-git/blob/4623fae42767ff41f309225f088fcfa6edea9ae3/src/commandsAndMenu.tsx#L605)

**Comment by fcollonval** [comment]
> For the rename commit, when we want to show the diff, are we still gonna use the renamed commit filename (`src/main.ts` from your example) only? Or should we do something like how VSCode does it, where left side is the old filename, and right side is the new filename?

I would go for the second option as a rename can also carry some changes (git is actually reported a percentage of changes when it detects a rename). So you are right, the object returns should be more complex. The key `from` like for file status sounds nice to store the original path.

**Comment by rfox12** [comment]
Would the use of `git mv` to rename a file alleviate the need to produce any special handling here?  Basically ensuring git can track the history as expected?
