### ISSUE TITLE
git folder not being recognized

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab-git#179]
This is with `jupyterlab` 0.31.1 and the latest master of `jupyterlab-git`.

In the terminal I'm seeing 404 messages of the form:
```
[W 15:45:45.040 LabApp] 404 POST /git/API?1516772745105 (10.200.18.81) 4.00ms
[W 15:45:52.422 LabApp] 404 POST /git/API?1516772752486 (10.200.18.81) 4.00ms 
[W 15:45:52.851 LabApp] 404 POST /git/API?1516772752917 (10.200.18.81) 3.99ms 
[W 15:46:00.031 LabApp] 404 POST /git/API?1516772760098 (10.200.18.81) 4.00ms 
```

![image](https://user-images.githubusercontent.com/881019/35316622-679d106e-011e-11e8-965b-2658e176d365.png)

**Comment by zzhangjii** [comment]
It seems to be problems with the server part, try re-install and activate the jupyterlab_git python handler package:
pip install -e . --upgrade

jupyter serverextension enable --py jupyterlab_git

**Comment by dhirschfeld** [comment]
Will give that a go & report back in the morning!

**Comment by dhirschfeld** [comment]
The install seemed to work:
```
C:\test\jupyterlab-git [master ≡ +1 ~1 -0 !]> jupyter serverextension enable --py jupyterlab_git
Enabling: jupyterlab_git
- Writing config: C:\Users\ContainerAdministrator\.jupyter
    - Validating...
      jupyterlab_git  ok
```
...but it hasn't changed the result:
> *Git-pulgin trackes the filepath in filebrowser, the current folder is not a git-repo* 

I'm in the `jupyterlab-git` folder in the FileBrowser which *is* a git repo.

NB: It would probably be useful to show the current folder name in the Git Tab:

![image](https://user-images.githubusercontent.com/881019/35363684-df62c920-01b6-11e8-8fbc-1812508495f8.png)

**Comment by zzhangjii** [comment]
So, does it still say 404 errors in the terminal? 
try the following steps for test:
1. open a terminal, enter the jupyterlab-git folder, start a jupyter lab there;
2. Check the jupyterlab filebrowser 'Files' and Git extension "Git", 
3. if the Git extension doesn't work, check the error message shown in terminal.

Thanks for the suggestion! Previously, the current path will be shown if Git detects it's inside a repo. It would make sense and be helpful to show it in the warning page as well!

**Comment by dhirschfeld** [comment]
> *So, does it still say 404 errors in the terminal?*

yes

**Comment by dhirschfeld** [comment]
> *open a terminal, enter the jupyterlab-git folder, start a jupyter lab there;*

That won't work since the `jupyterlab-git` repo is in a Windows Container and I'm accessing it from the terminal in JupyterLab itself.

i.e. I'm trying to add the `jupyterlab-git` extension to the running JupyterLab session. After refreshing (Ctrl-F5) the Git tab appears but it doesn't recognise git folders and I get the POST 404s shown above

**Comment by zzhangjii** [comment]
That should be the issue, the server extension hasn't been tested for Windows system. Probably the handlers can't be detected in Windows, so got 404 errors.

**Comment by epifanio** [comment]
Hi,
I hope this is the right place where to report my issue.

I'm running JupyterLab from a `jupyterhub` instance. 
The git extension got correctly installed, I can see a git tab on the vertical panel on the left and in the menubar on top, however the extension doesn't recognize the working directory as a git repository.
 
**Error:** The current folder is not a git repository. Please make sure you are currently working in a git repository in order to use this plugin.


If, from the same machine, I run a single user JupyterLab instance, and I navigate with the file browser a git repository, the `git extension` works  just fine(btw, great extension!!!) 

Is there anything I can do to help devs to debug the jupyterhub deployment of the extension?

From the js console I can read:
```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (API, line 0). https://myhost:9000/user/epinux/git/API?1234567891234
```

**Comment by epifanio** [comment]
Hi @zzhangjii,  yes, I did run both those instructions. On the single user istance it works fine.

**Comment by zzhangjii** [comment]
@epifanio well, maybe it's the python environment? check [issue #185](https://github.com/jupyterlab/jupyterlab-git/issues/185)  to see if it helps, ex: install the handler on the proper path. 
Currently I have trouble testing it on my system, will try to re-produce and solve the problem next week.

**Comment by epifanio** [comment]
I tired to locate the files on the server, 

```
sudo updatedb
 locate jupyterlab-git-
````
 returns a single entry in:

```/usr/local/share/jupyter/lab/extensions/jupyterlab-git-0.1.1-12f97290b2c90bd3afcee4d9979a1c6fb52ce9d8.tgz```

**Comment by AmadeusSG** [comment]
I think I may have found the issue here; the git extension doesn't recognise extra prefixes to the path that it supposed to be at. Currently I also have a multi-user JupyterHub set-up with JupyterLab interface, with the added jupyter-git extension (using the package.json hack by @zzhangjii)

For example, by default JupyterHub starts the server at `/home/user/`. However, I made it such that the root folder of the JupyterHub is at `/home/user/JupyterHub/` instead. This may interfere with how it searches for the current folder using the `Files` tab.

So, for example, the intended repo directory to use the `Git` tab is at `/home/user/JupyterHub/myrepo/`. However, the `Git` tab may be referencing this as `/home/user/myrepo/` instead. So I'm wondering if anyone can tell me where to change the reference point to attempt to solve the issue.

How I got this suggestion is to use `Open Terminal` in the upper menu's `Git` tab. When I click on it, it shows me that it does a `cd myrepo` instead of `cd JupyterHub/myrepo`, which resulted in a path error. 

I may be wrong in the diagnosis of the issue though, as I did copy `myrepo` to `/home/user/myrepo` to check whether the `Git` tab identified the folder as a git directory, but to no avail. But hopefully this finding may lead someone to find a better path to fix this issue.

**Comment by hjalmarlucius** [comment]
@AmadeusSG I have this very same issue of the `Git` tab looking in the wrong folder

**Comment by dunjoye4real** [comment]
I have the same issue with Git tab looking in the wrong folder. I tried to use open terminal from `Git` menu and i figured out jupyter-lab is referencing from `/home/username/` which apparently, i started jupyterlab from that path, fine. I did a `git init` in this same folder `/home/username/` but jupyterlab-git could not still recognise the folder as a git repository even after multiple restart.
I could do all `git` task in this repository but jupyterlab-git extension can't recognise it as a git repository.
Kindly, @zzhangjii  @AmadeusSG  @hjalmarlucius  does anyone know a fix for this issue?

**Comment by rokroskar** [comment]
Is the "Go find a repo" button supposed to set the base git directory? In my case it takes me to the correct directory which contains the git repo (`/home/jovyan/work` in this case) but then I have no way of telling the git extension to go there.

**Comment by AljoLe** [comment]
Same problem here.
I've got jupyterhub running on a fedora 28 linux machine and notebook or normal jupyterlab run just fine. I only see the "Go find a repo" button and above it stand "You aren’t in a git repository.". When I hit the button, the file tab comes in focus, like clicking on it, but nothing else happens.

**Comment by neuromusic** [comment]
same 404 errors here, on Ubuntu 18.04. Jupyter Lab is launched with notebook_dir set in a config file. going to try #210

**Comment by Mayurji** [comment]
Hi Team, 

We have setup a kubeflow environment where we are running our Notebook server. We are able to clone the repository, but when we click the git icon on JupyterLab for the cloned repo, we are unable to see branch or changes. It still shows the below message 

_You are not currently in a Git repository. To use Git, navigate to a local repository, initialize a repository here, or clone an existing repository._

**FYI**

while cloning the repo in jupyterlab, we see a log on notebook server as follows

`E 2024-02-07 12:28:40.798 ServerApp] 500 POST /notebook/project-name/test-git-nb/git/clone?1707308919343`
`[E 2024-02-08 05:10:26.071 ServerApp] 500 POST /notebook/project-name/test-git-nb/git/show_top_level?1707369025823`

Next, we also checked if jupyterlab_git is enabled

`    Validating jupyterlab_git...

       jupyterlab_git 0.30.1 OK
    - Extension successfully enabled.`

`
@jupyterlab/git v0.30.1 enabled OK (python, jupyterlab-git)
`

How to move forward with this issue?

**Comment by fcollonval** [comment]
Hey @Mayurji 

Please open a new issue instead of using a closed one.

The first advice I would give you is to use a more recent version. 0.30.1 is very old.
