### ISSUE TITLE
Iconography updates

### ISSUE THREAD

**Issue by weihwang** [jupyterlab/jupyterlab-git#249]
Proposal to update iconography
https://www.figma.com/file/UyNpeQNuTj6Uv74MoEJDh3ji/Git-extension?node-id=606%3A1844

New actions:
- Push/Pull (pending feedback on #246)
- Add repo
- Diff
- Setting (possible future addition)

Updates:
- File status: updating from 3 letter icon to single letter higher contrast icons

All icons
![image](https://user-images.githubusercontent.com/551333/47170878-20285980-d2bc-11e8-8c31-55bf964745f4.png)

![image](https://user-images.githubusercontent.com/551333/47171058-91680c80-d2bc-11e8-90cd-ccca7554c6bc.png)

Impact to commit change detail (related to #227)
![image](https://user-images.githubusercontent.com/551333/47047080-8346ae80-d14b-11e8-828a-ed077c180a25.png)

Impact to file browser view (related to #124)
![image](https://user-images.githubusercontent.com/551333/47047113-99546f00-d14b-11e8-8adb-af785ae13329.png)

**Comment by dhirschfeld** [comment]
Looks awesome! Just a few comments which you can take or leave:
 - The clone repo icon doesn't scream "clone" to me but I'm not sure anything is obviously better. Maybe some combination of the download/pull icon and the git icon?
![image](https://user-images.githubusercontent.com/881019/47058213-77b8bd80-d207-11e8-95c9-2b36fd3cc660.png)
 - The discard trashcan icon seems a little alarming - i.e. might get confused for deleting the file rather than discarding the changes. An undo (rewind arrow) icon might be less alarming whilst conveying the same message
 - The view diff icon is somewhat ambiguous but I'm also not sure what is better. Perhaps we could get away *without* a diff icon though if clicking on the file in the changes view *automatically* brought up the diff view. This is the behaviour of VSCode and something I *really* like about it. For me, being able to easily view/understand the changes which will be committed is critical so anything which lowers the barrier to that is great. If the diff view is brought up automatically when you click on a file (in the changes view) then it's one less click the user needs to do.

**Comment by weihwang** [comment]
@dhirschfeld great feedback, thanks! I saw another comment on the "delete/trashcan" so let me take a pass at the "undo" arrow.

On the diff action, if clicking on the filename and always showing the diff is reasonable, not just showing the file itself, I'll remove the diff icon proposal. This helps simplify the actions column too.

**Comment by jaipreet-s** [comment]
@weihwang We should also have a disabled state for the `Clone git repo` icon for the case when the clone button will be disabled if we are already inside a Git repo. (Subtask 3 in #253 )

**Comment by weihwang** [comment]
Added disabled git clone, undo. Removed "diff" since we can use the filename for the action.

**Comment by weihwang** [comment]
Added dark theme icons

**Comment by weihwang** [comment]
While I agree a save icon might be more intuitive, we need something that can support directional actions of push/pull, and save seems like it supports only one category. I've considered the upload/download but those icons are used for staging/unstaging at the moment. This will require some additional review.

**Comment by fcollonval** [comment]
@telamonian @kgryte should we close this rather all issues. And let people start new issues based on the latest styles.

**Comment by kgryte** [comment]
I am okay with closing this issue given recent changes.
