### ISSUE TITLE
View diff on filename click

### ISSUE THREAD

**Issue by weihwang** [jupyterlab/jupyterlab-git#252]
Proposal to connect filename double click in a commit detail view or working changes list view to the file diff view. V1 will open a terminal, with an improvement to a graphic interface view.

![image](https://user-images.githubusercontent.com/551333/47106674-14755e00-d1fc-11e8-825d-9ab2c14e27df.png)

![image](https://user-images.githubusercontent.com/551333/47106649-04f61500-d1fc-11e8-8675-fae586b80616.png)

**Comment by dhirschfeld** [comment]
+:100:!

I like how in VSCode you only need to select a file for it to show the diff. This however probably works best with VSCode's concept of a temporary view of the file - i.e. as soon as you select a different file the old view is *replaced*  with the view of the new file. This works since you wouldn't want simply selecting files to leave dozens of tabs open. To get a permanent tab you have to actually double-click the file.

**Comment by weihwang** [comment]
@dhirschfeld Thinking about the single click, it seem pretty heavy to render a diff view. Also this requires a change to the behavior of Jupyterlab to support single-persistent window that changes on each single-click. In that use-case, if supported, would a diff view usually be expected to be the default view as opposed to just the current state of the file as an easy browse interaction?

I think it would break down to separate tasks:
1. Should we support single-click persistent window reload for file "preview/browse"
2. If supported, should this experience show "diff" view vs. "current" view?

**Comment by dhirschfeld** [comment]
The single click open is what is known as [Preview Mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode) - you can click-browse through files without cluttering your workspace with multiple tabs. When you find the file you're interested in you can double-click it to make it *sticky* - i.e. to persist when you click/open a new file

**Comment by fcollonval** [comment]
Although we don't have a _Preview Mode_, the feature is in now. So I close this issue.
