### ISSUE TITLE
commit a change

### ISSUE THREAD

**Issue by sche0025** [jupyterlab/jupyterlab-git#282]
After I commit a file in **Staged**, this file does not go to **Changed**, however, if I edit this file again, it will appear in **Changed** directly( this is not reasonable since I have not committed this change ). So could someone tell me how to fix this?

**Comment by jaipreet-s** [comment]
From what I can tell this is the general behavior of how Git reports file statuses.
```
touch $filename
git add $filename
git commit -m "Changed file name"
```
- At this point you have no changes in staging or Modified
```
vi $filename
```
- At this point, your file will come up as "Modified" since its different from what was commited.


The UX will roughly mirror what you get after `git status`. Let me know if I misunderstood

**Comment by sche0025** [comment]
@jaipreet-s 
First， thank you for your answer.
If I understand correctly, you were referring that this outcome is normal. However in my understanding of this add-on:
         track is equivalent to git add, which moves files from **Untracked** to **Staged**;
         the commit is used to commit the change locally, so after this operation, this committed file should go to **Changed**.
Could you tell me where I misunderstood?

**Comment by sche0025** [comment]
@jaipreet-s it seems that I understand what's going on, thank you !

**Comment by jaipreet-s** [comment]
Glad to help @sche0025!
