### ISSUE TITLE
push and pull fail, GIT_TERMINAL_PROMPT=0 command not found

### ISSUE THREAD

**Issue by mschroen** [jupyterlab/jupyterlab-git#291]
A fresh install of the jupyter-lab git extension, stage and commit on an existing git repository works fine. However, pressing the button `push` fails with a message just saying `Push failed`. In the terminal protocol, it says 
```
[E 13:29:11.800 LabApp] 500 POST /git/push?1544963351615 (::1) 124.80ms referer=http://localhost:8916/lab
```
Pressing button `pull` fails with a message `The command ""GIT_TERMINAL_PROMPT=0 git pull --no-commit"" is either misspelled or could not be found.`. No terminal message protocolled. 

My Git by default uses saved credentials, so there is no need to prompt for username/password.
I never had problems using git on my system, both with the terminal commands or with third-party software, so it must be an issue related to jupyter lab. The command `GIT_TERMINAL_PROMPT=0 git pull --no-commit` works fine when I execute it in my shell (cygwin's mintty). It does not work (CommandNotFound) in PowerShell, however, which opens when I go to Git>Open terminal in the jupyter lab menu. But I never use PowerShell for anything, so I see no reason why PowerShell is used here.

Does jupyter lab/git use the PowerShell? I this the reason for the commands to fail (it looks to me that PowerShell cannot handle prefixes like `GIT_TERMINAL_PROMPT=0` before the actual command... Can I tell jupyter lab/git not to use PowerShell?

I am on Windows 7, Python 3.6.0 and Git 2.11.1 installations (not under cygwin), and jupyter lab 0.35.4.

**Comment by fcollonval** [comment]
Thanks @mschroen for reporting this issue. 
I got it too and I can explain the root cause:
The reason this is failing is Windows. 
`GIT_TERMINAL_PROMPT=0` is only valid in Unix and Mac OS worlds to set an environment variable but not in windows. So this explain why you succeed to use it with cygwin shell but not in Powershell.

> Can I tell jupyter lab/git not to use PowerShell?

Unfortunately the commands is launched by the extension via a subprocess, meaning  on windows `cmd`. And there is no way to change this - as far as I know.

So as dirty fix,  you need to go into your python installation in the `jupyterlab_git` package and remove every occurrence of `GIT_TERMINAL_PROMPT=0`.

For the dev,  would it work to use `os.environ` instead of the current trick to support windows too?
