### ISSUE TITLE
Add prompt for user credentials

### ISSUE THREAD

**Issue by n-a-sz** [jupyterlab/jupyterlab-git#299]
The push/pull/clone functionality cannot be really used without setting up an ssh key or an access token using the console. However, JupyterLab users don't necessarily have the knowledge of even using a terminal.

It would greatly add to the value of the plugin if the user could type their username and password when pushing/pulling/cloning.

**Comment by jaipreet-s** [comment]
Hi @n-a-sz ,
The extension doesn't perform credential management because different sets of users would want their credentials to be handled in their own way.

However, I think it's a reasonable expectation to prompt the user for credentials and use them *without storing*

The user would still be prompted every time they did a push or pull however we could point to the [git credentials](https://git-scm.com/docs/gitcredentials) documentation to aid them in persistently setting up credentials

**Comment by ktaletsk** [comment]
I'm working on implementing this feature. I had it working to allow users to authenticate in git without storing anything. On backend, this was achieved by using `pexpect` instead of `subprocess.Popen`. Unfortunately, since I started working on that (I forked from https://github.com/jupyterlab/jupyterlab-git/tree/01d130f28f31876b4962f2637d97e118f1281246), pull/push UI has changed in a way that made it harder for me to implement that (clone is working fine). Before the changes I was overloading `PathHeader`'s `executeGitPush` to call API in a while loop:
```
//Existing method
private executeGitPush(): void {
    this.state.gitApi.push(this.props.currentFileBrowserPath)
      .then(response => {
        if (response.code != 0) {
          this.showErrorDialog('Push failed', response.message);
        }
      })
      .catch(() => this.showErrorDialog('Push failed'));
  }
```

```
//My modification
private executeGitPush(): void {
    this.state.gitApi.push(this.props.currentFileBrowserPath)
      .then(async response => {
        let retry = false;
        while (response.code != 0) {
          if (response.code == 128 && (response.message.indexOf('could not read Username')>=0 || response.message.indexOf('Invalid username or password')>=0)) {
            const dialog = new Dialog({
              title: 'Git credentials required',
              body: new GitCredentialsForm('Enter credentials for remote repository', retry ? 'Incorrect username or password.' : ''),
              buttons: [
                  Dialog.cancelButton(),
                  Dialog.okButton({label: 'OK'})
              ]
            });
            const result = await dialog.launch();
            dialog.dispose();

            if (result.button.label == 'OK') {
              //user accepted attempt to login
              let auth_json = JSON.parse(decodeURIComponent(result.value));
              //call gitApi.push again with credentials
              let auth: authObject = {
                username: auth_json.username,
                password: auth_json.password
              }
              response = await this.state.gitApi.push(this.props.currentFileBrowserPath, auth);
            }
            else {
              //user cancelled attempt to log in
              this.showErrorDialog('Push failed');
              break;
            }
            retry = true;
          }
          else {
            this.showErrorDialog('Push failed', response.message);
            break;
          }
        }
      })
      .catch(() => this.showErrorDialog('Push failed'));
  }
```

The only way I see it working now, is to recursively call `executeGitApi` from the constructor.
I would like an advice from maintainers on what would be the better way to modify `GitPullPushDialog` class to be able to call pull/push API `executeGitApi` more than once, similar to my previous changes.

**Comment by saulshanabrook** [comment]
I will review this tomorrow. Thank you for putting this together!

**Comment by mirestrepo** [comment]
This would be a great feature! Are there any news?

**Comment by ktaletsk** [comment]
@mirestrepo I had it implemented couple of months ago but never got merged. Since then there were a lot of changes in the extension (Identity feature, moving to Jupyter Lab 1.0, etc). If there is still interest I can update it for the latest version and get ready for merging again. @saulshanabrook what do you think?

**Comment by DraTeots** [comment]
We need this. Really

**Comment by ktaletsk** [comment]
@n-a-sz @mirestrepo @DraTeots the Simple Auth feature has been merged. Please, give it a try and report any issues here.

**Comment by fcollonval** [comment]
Closed by #345

**Comment by akaihola** [comment]
#345 doesn't implement a GUI for entering an SSH passphrase, right?

**Comment by fcollonval** [comment]
> #345 doesn't implement a GUI for entering an SSH passphrase, right?

Indeed it will not work. But PR are welcomed.
