### ISSUE TITLE
In the Jupyterlab terminal, git diff output is hidden

### ISSUE THREAD

**Issue by danielsparing** [jupyterlab/jupyterlab-git#334]
In the Jupyterlab terminal, `git diff` does not print its output.
(Maybe it is part of `nbdime` or the `git` integration? Not sure.)

I am able to make it work with `git diff | cat` or similar, but at least a more helpful warning message would be useful.

**Comment by jaipreet-s** [comment]
The Git extension does not interfere with what you execute in the JupyterLab Terminal. 

For example, I'm able to see the git diff in a JupyterLab installation with the Git extension 

Could you please share more details on what/how this issue is occuring?


![Screen Shot 2019-04-10 at 10 57 28 AM](https://user-images.githubusercontent.com/43826141/55902073-8e6d1b00-5b7f-11e9-8d9b-255261f4f1eb.png)

**Comment by jasongrout** [comment]
Thanks for following up on this, @jaipreet-s.

**Comment by danielsparing** [comment]
Apologies, after taking a second look indeed the issue is somewhere else in my installation, closing.
