### ISSUE TITLE
jupyterlab-git push returns an error (with GUI), while "git push" on the terminal works

### ISSUE THREAD

**Issue by RanFeldeshKik** [jupyterlab/jupyterlab-git#348]
* jupyterlab-git GUI works for staging and local commits (thanks!). However, **when attempting to push (pressing the cloud icon) - an error message appears**: "Push failed git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists."
* However, **when running from the terminal the command "git push" does the push right away** (i.e. no password or passphrase are requested; no sudo is needed). This is done through SSH, with a passphrase that was saved by ssh-agent).
I am running on Littlest Jupyter Hub on Ubuntu 18.04.

What could be the reason for this behavioral discrepency between the (great) GUI and the command line?

**Comment by RanFeldeshKik** [comment]
This seems to be an issue with the passphrase being stored only within the terminal session in which it was created. Closing this, as it is unrelated to jupyterlab-git specifically.

**Comment by ttadesusi** [comment]
I am having the same issue.

Please have you found a solution to this?

**Comment by snoehmer** [comment]
Hi,
I just installed the jupyterlab-git extension and have the exact same issue. I have tried everything I could think of, but could not get pull/push to work with my GitHub account. Maybe someone can give me a hint what I am doing wrong?

As the original poster, git works as it should when I use terminal commands in the JupyterLab console (or any other terminal). I use `keychain` for adding/unlocking SSH keys, which works properly (I have also tried `ssh-agent`, same results). However, if I use the GUI button for push/pull, I get the same error message (`Permission denied (publickey)`).
Because SSH keys are stored only within the terminal session, I switched to `keychain` as SSH agent, which should keep the SSH keys for all future sessions after the passphrase is entered once (after first login). For the terminal, this works - I can use the SSH key in all terminal sessions after I have entered the passphrase. However, it seems not to work in the JupyterLab GUI.

I have tried changing the remote URL to HTTPS, where push/pull worked without a problem in JupyterLab via GUI. After changing the URL back to SSH, I get the permission denied errors again. So, everything works properly with HTTPS, but not with SSH connection. Frankly, I want to avoid having to enter my username and password, and use my SSH key instead.

Does anyone have a solution for this? Or hints what the problem could be? I am wondering what I am doing wrong.
Thanks. And thanks for all the work creating this git extension!

**Comment by ttadesusi** [comment]
Thank @snoehmer 

Please could give us a step by step process on where to locate the JupyterLab systemd unit file on a windows pc so that I reconfigure the "ExecStart" as you suggested.

**Comment by snoehmer** [comment]
Hi @ttadesusi,
sorry I didn't mention that, the above fix only applies for Linux systems.
Maybe it is the same problem, where your SSH key needs to be unlocked via passphrase for the session JupyterLab is running in. Are you using any Git credential manager to manage the SSH keys? e.g. the credential manager that is shipped with Git for Windows. (please see https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage)
Sorry, I don't run JupyterLab on any Windows machine, so this is just guessing.

**Comment by bjornjorgensen** [comment]
@snoehmer what did you change in [docker-stacks base notebook](https://github.com/jupyter/docker-stacks/tree/master/base-notebook) and what is "proper ssh-agent/keychain initialization in ~/.bash_profile"

**Comment by snoehmer** [comment]
Hi @bjornjorgensen,
sorry, I don't use docker for running JupyterLab, therefore I can't really help with that. I am just running a standalone instance.
Anyway, the proper ssh-agent initialization is described for example in the Arch Linux wiki: [https://wiki.archlinux.org/title/SSH_keys#SSH_agents](url)

**Comment by Markook** [comment]
@snoehmer did you make any changes to the ~/.bash_profile? I am trying to figure out how to make this owrk

My systemd service looks like this originally:
```
[Service]
ExecStart=/home/magic/anaconda3/bin/jupyter-lab --config=/home/magic/.jupyter/jupyter_notebook_conf
```

Turned it into this:
...
ExecStart=/etc/profile -l -c "/home/magic/anaconda3/bin/jupyter-lab --config=/home/magic/.jupyter/jupyter_notebook_config.py
...

and my etc/.profile file looks like this:

```
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "$(id -u)" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
```

**Comment by snoehmer** [comment]
Hi @Markook,
sorry for the late answer, I hope it still helps.

First, you seem to have an issue in your systemd service - in the `ExecStart` line, you should have `/bin/bash ...` instead of `/etc/profile ...`:
```
ExecStart=/bin/bash -l -c "/home/magic/anaconda3/bin/jupyter-lab --config=/home/magic/.jupyter/jupyter_notebook_config.py"
```

And yes, to include/unlock your SSH key, you need to add the appropriate initialization command to your bash config. Where to add the command is a bit out of the scope here, and also Ubuntu seems to have some quirks regarding the bash profiles. Since I could not find a good overview in the official Ubuntu wiki, please check this translated article from the very good German ubuntuusers.de wiki:
[https://wiki-ubuntuusers-de.translate.goog/Umgebungsvariable/Dateien/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp#Environment-einzelner-Dienste](https://wiki-ubuntuusers-de.translate.goog/Umgebungsvariable/Dateien/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp#Environment-einzelner-Dienste)
If you want to add it to your system profile, you should not use `/etc/profile` directly, but create a file under `/etc/profile.d/`. However, adding it to a user profile should be sufficient (and also adding it to the system profile may have security implications).

In my circumstances, I have added the command to the `~/.bash_profile` file for the corresponding user running the service (e.g. `/home/USER/.bash_profile`), which works well for me.

Also, the command you need to add depends on the SSH agent you are using. Please see the excellent Arch Linux wiki article for further information:
[https://wiki.archlinux.org/title/SSH_keys#SSH_agents](https://wiki.archlinux.org/title/SSH_keys#SSH_agents)

Again, in my case using `keychain` as SSH agent, I needed to add the following line to `~/.bash_profile` :
```
eval $(keychain --eval --quiet KEY_NAME)
```
(with `KEY_NAME` replaced by the actual file name of your key, e.g. `id_rsa`)

Please keep in mind that you need to unlock your SSH key at some point. To do that, it should be enough to open a terminal session as the user you are running the service. When the initialization command is run while the `~/.bash_profile` is processed, there should be a query for your key's passphrase. Upon entering the correct passphrase, your SSH key should be added to your SSH agent, and you should be good to go.
