### ISSUE TITLE
Reorganize menu items

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#456]
The "Git" menu is in need of a reorg (we definitely don't need a menu item that clicks the sidebar button for the user, and a menu item that opens a new terminal and `cd`'s to the current dir is too general. It should maybe be in the main jlab "File" menu, tho). That's yet another separate issue though.

_Originally posted by @telamonian in https://github.com/jupyterlab/jupyterlab-git/pull/448#issuecomment-557371937_

**Comment by telamonian** [comment]
I vote that we prune the:

- "Git Interface"
- "Git Command in Terminal"

menu items for the reasons stated in the first post above. 

If not pruned, at the least the "Init" item needs to be greyed out when the user is currently in a valid repo.

As to what actions should be in the Git menu, here's one possible minimal list:

- Init
- Push
- Pull
- Rebase

These all make sense to one extent or another. If anyone has strong feelings one way or another about what should get included in the "Git" menu, please comment below. Otherwise, I'll get around to a PR with the above proposal.

**Comment by fcollonval** [comment]
I agree on the proposed changes. But I would keep the open terminal in current repo feature at some other place.

We could add it at the top of the sidebar with the push and pull buttons and have the repository path below like for the filebrowser. 

Note: I'll try to find time to add a feature for pinning the repo path.

**Comment by fcollonval** [comment]
It may be interesting to add :

* Clone
