### ISSUE TITLE
Bug: scroll bar for the all panel not for the file list

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#524]
## Description

When there are lots of modified files, the scroll bar appears on the all git panel. It should be restricted on the file list.

![image](https://user-images.githubusercontent.com/8435071/72351965-aca11200-36e1-11ea-8d69-9959c7b70de2.png)

## Reproduce

1. Launch binder on master
2. Reduce the window height to have the scroll bar appearing

## Expected behavior

Scroll should be on the file list only. The toolbar and the commit box should be all the time visible.

**Comment by kgryte** [comment]
I **don't** agree with the expected behavior being that the toolbar and commit box should be visible at all times (e.g., such as when the branch menu is shown).

We could, however, assign a maximum height to the file list container to prevent extra long scrolls to reach the commit box when, say, there might be thousands of changed files, but this would not obviate the need to scroll when window heights are smaller.

I should be able to address this in #518, as I've already had to adjust the file list container styling.

**Comment by fcollonval** [comment]
Committing files is in the top features used. When an user switch to the Git tab, especially in the simple mode, lots of time the goal will be to enter a commit message and hit the commit button. I personally will never expect to have to scroll to do that.

So in the default layout (no branch menu deployed):
- the commit box must be visible what ever the number of changed files.
- the toolbar should be visible as it provides the repository context.

In the branch menu layout, @kgryte you rise a good point. I don't know how to address it nicely while not breaking the default layout behavior. 

@tgeorgeux could you please give us your recommendation on this?

Note: Hiding the file list is the behavior of [GitHub Desktop](https://i.imgur.com/hYVhufe.png).

**Comment by fcollonval** [comment]
Solve by the various style fixes in 0.10.0
