### ISSUE TITLE
git extension for dev mode

### ISSUE THREAD

**Issue by mail2julian** [jupyterlab/jupyterlab-git#531]
## Description

How to enable the git extension for jupyter lab in dev mode.

**Comment by telamonian** [comment]
Don't.

If you really need to, you can do a [sibling install](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#extension-authoring) of the jupyterlab-git extension into a development branch of Jupyterlab. But seriously, don't do this, we do not support this use case. Sibling installs do not work well, and often require significant manual debugging.

The only exception to the above is if you're trying to develop a feature in jupyterlab core alongside a feature in this extension (eg you want to expose the filebrowser from core so that it can be reused in this extension). Then (and only then) is it worthwhile to go through the trouble of doing a sibling install
