### ISSUE TITLE
Commit Greyed Out

### ISSUE THREAD

**Issue by AyrtonB** [jupyterlab/jupyterlab-git#639]
Hi all. I'm trying to push a new commit but the button is greyed out, i've already made sure to pull latest changes etc. Any help would be much appreciated!
![image](https://user-images.githubusercontent.com/29051639/82210383-e8a1e900-9906-11ea-817a-af7bcbe6da84.png)

**Comment by fcollonval** [comment]
Hey @AyrtonB did you find the error? Is there something to change in the extension?

**Comment by ianhi** [comment]
Even if there was no error it might be nice to change the title attribute of the commit button to reflect why it is disabled. It can be disabled due to no text in commit message, or no files staged.
https://github.com/jupyterlab/jupyterlab-git/blob/e923a5beeb5f29ab16085e4a28efeae785128280/src/components/CommitBox.tsx#L70
https://github.com/jupyterlab/jupyterlab-git/blob/e923a5beeb5f29ab16085e4a28efeae785128280/src/components/CommitBox.tsx#L90-L97

**Comment by AyrtonB** [comment]
> Hey @AyrtonB did you find the error? Is there something to change in the extension?

Hi @fcollonval. It seemed to be a transient issue, when I reloaded the page I was able to click it.

**Comment by fcollonval** [comment]
Thanks for the answer @AyrtonB.

**Comment by ianhi** [comment]
Hi @vrtoaso when you hover your mouse over the button what does the text say?

**Comment by vrtoaso** [comment]
HI ianhi, thank you for following up. It originally said "Disabled: No files staged for commit" although I did stage the files. Since I posted this I've restarted my machine - now when I add the file (via the plus) the COMMIT button is green. I read about refreshing or closing and reopening the browser, which I did, but apparently the restart worked.

This matter is resolved. I appreciate the collaboration.
