### ISSUE TITLE
Ignore Notebook UI

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab-git#683]
## Description

It's useful to declare some notebooks should not be stored in git. In git, this is accomplished by adding something to a `.gitignore` file. I propose we add an ability to right click on one or more files in the git extension and choose to ignore it. This would add a single line to `.gitignore`. To be clear, I am not proposing we commit the change - that's up to the user.

**Comment by ianhi** [comment]
That seems useful. A set of options might look like:
- Add file to gitignore
- Add filetype to gitignore
- (for folders only) add folder to gitignore

**Comment by kgryte** [comment]
@mlucool I am guessing you have in mind a "non-technical" JupyterLab user? Otherwise, for those familiar with Git and using `.gitignore` files, they could simply edit a `.gitignore` file directly in JLab to ignore a file, file type, and/or folder.

For the non-technical user, I am not sure if adding something to `.gitignore` but not committing the changed `.gitignore` is ideal. Suppose a user opts to ignore a folder via a context menu, but never commits the changes to the `.gitignore`. Later, they switch computers (work to home), create a folder which would have been ignored on the other computer, and it gets accidentally committed because they forgot to "ignore" it before staging and committing all files.

Or suppose a user ignores a file, never commits the changes to `.gitignore`, someone else collaborating on the same repository creates a file with the same name, commits it, and then the original user pulls changes and now has a clash and a potential undesired outcome.

Granted, the above can already happen when collaborating and directly using `.gitignore` files. My main hangup is that a user may be led to believe that, by clicking "ignore", a file, file type, and/or folder will be ignored forever, and, thus, be a bit surprised when they pull down changes and see a file type or folder they assumed would be ignored.

In general, while the above may be "edge" cases, I'd like to avoid creating UI behaviors which can lead to unexpected outcomes. I would think that, assuming we were to add support for ignoring files, file types, and/or folders, then we should automatically prompt a user to commit the change to `.gitignore`. This forces the user to be explicit and should help mitigate unexpected outcomes.

Also not clear to me how patterns should be automatically generated. If we are in a nested folder and a user opts to ignore all files having extension `*.foo`, then should the pattern added to the `.gitignore` file be based on the nested folder or apply to the entire repository? Similar for a file. Should only the file basename be added to the `.gitignore` file or should the complete relative path? Same thing for a folder. Just the folder name (in which case all matches folders are ignored) or the path?

At the moment, a user can already effectively "ignore" a file by never staging it (when simple staging is **disabled**). The Git UI will continue to "track" it as unstaged, but never add it to the tree.

On my end, I think I'd need a bit more clarity on how adding this functionality would work in practice. There may be a temptation to just limit it to individual files, such as notebooks; however, once we add a UI for ignoring a particular file, we will inevitably be asked to support more general ignore patterns (e.g., file types and folders), so we'd need a compelling reason why we can't support those use cases, or we'd need some idea how we'd go about implementing more general ignore support.

**Comment by mlucool** [comment]
In both view - simple staging and not - it would make sense that ignored files don't show up at all in the git interface as you can't take any operation on them. This is consistent with `git status`.

In my view, committing is fraught with edge cases. What is someone had some pending changes in `.gitignore` already? Instead, I'd recommend we copy what the major editors do in this case. Intelleji allows you to ignore a file only if it has not been committed or any folder (even if there are committed files in it - which I am not sure is right). When you click ignore, it opens up the .gitignore file to make it very clear what was done, which I quite like. Maybe as a next step we gather what VSCode and other places with a git UI offer to compare?

>  I am guessing you have in mind a "non-technical" JupyterLab user? 

As a more technical user I'd use this too if there was multi-select. Single click at a time would be too much work and I'd go back to `.gitignore`.

**Comment by echarles** [comment]
Hi, I have opened https://github.com/jupyterlab/jupyterlab-git/pull/705 PR for this.

**Comment by ianhi** [comment]
I am a big fan of this change, I too am a technical user and have at times wanted this feature. Also I'm pro multiselect (there's an existing issue https://github.com/jupyterlab/jupyterlab-git/issues/379)

> they could simply edit a .gitignore file directly in JLab to ignore a file, file type, and/or folder.

Unfortunately jlab doesn't show hidden files or folders in the filebrowser by default (https://github.com/jupyterlab/jupyterlab/issues/2049) so I always find myself opening a system terminal to add something to my gitignore file. 

> Also not clear to me how patterns should be automatically generated. If we are in a nested folder and a user opts to ignore all files having extension *.foo, then should the pattern added to the .gitignore file be based on the nested folder or apply to the entire repository? Similar for a file. Should only the file basename be added to the .gitignore file or should the complete relative path? Same thing for a folder. Just the folder name (in which case all matches folders are ignored) or the path?

I agree that this is tricky. For context all of the other Git interfaces I tested added the full path when a specific file was added and just add `*foo` for all files of a type. As for folders they don't currently appear in the Git panel and so would not be ignorable, however I think that if they were to be we would follow the convention with files and just ignore the specific path.

> That, by clicking "ignore", a file, file type, and/or folder will be ignored forever,

I think this problem we could be mitigated by being very explicit with the language used in the menu item. 
- `Add this file to gitignore`
- `Add *.foo` to gitignore


## What other git UI's do:
I think that github desktop is the best one to emulate here as it is it the most explicit about what is happening.

**github desktop**
![image](https://user-images.githubusercontent.com/10111092/88459491-e8bce880-ce63-11ea-9c03-2145ee6661d5.png)

**vscode**
![image](https://user-images.githubusercontent.com/10111092/88459514-fa05f500-ce63-11ea-812d-7ddcafbf6bcf.png)

**git cola**
![image](https://user-images.githubusercontent.com/10111092/88459545-36395580-ce64-11ea-8119-444a93953792.png)

**Comment by echarles** [comment]
> Also I'm pro multiselect (there's an existing issue #379)

Yep, once multiselect will be avaibalbe, we can roll that out for gitignore.

> Unfortunately jlab doesn't show hidden files or folders in the filebrowser by default (jupyterlab/jupyterlab#2049) so I always find myself opening a system terminal to add something to my gitignore file.

Sounds like `jupyter lab --ContentsManager.allow_hidden=True` can help - After all if it is an "hidden" file, it should be hidden by default...

> I think this problem could be mitigated by being very explicit with the language used in the menu item. 1) e.g.: Add this file to gitignore 2) Add *.foo to gitignore

Good call: 2 menu items (only one if the file has no extension)

**Comment by ianhi** [comment]
> Sounds like jupyter lab --ContentsManager.allow_hidden=True can help - After all if it is an "hidden" file, it should be hidden by default...

Indeed, but most people will probably not be starting their jupyterlab with that option. I know about it and I still don't :joy:. While .gitignore is a hidden file that it seems to me you would want access to from your editing environment. For example vscode: 
![image](https://user-images.githubusercontent.com/10111092/88483428-ddd28880-cf35-11ea-9623-20f1bb4da0a2.png)

I don't think that jupyterlab will be changing the defaults w.r.t hidden files anytime soon and `.gitignore` is a pretty important file to be able to modify. What if the `Git` menu provided an `Open .gitignore` option to make it possible to easier access to this file from within jupyterlab?

**Comment by fcollonval** [comment]
> What if the `Git` menu provided an `Open .gitignore` option to make it possible to easier access to this file from within jupyterlab?

I think this is a good idea. So advanced user can easily work with it. But other hidden files stay hidden.

> Sounds like jupyter lab --ContentsManager.allow_hidden=True can help - After all if it is an "hidden" file, it should be hidden by default...

@echarles Do you think it would make sense to implement in the content manager frontend to switch this without a need for restarting?

**Comment by kgryte** [comment]
@ianhi I agree. Adding a Git menu option seems reasonable.

**Comment by echarles** [comment]
> @echarles Do you think it would make sense to implement in the content manager frontend a switch to remove the need for restarting?

Just opened https://github.com/jupyterlab/jupyterlab/issues/8724 to track this.
