### ISSUE TITLE
Is it possible to display commit description?

### ISSUE THREAD

**Issue by XiaomoWu** [jupyterlab/jupyterlab-git#685]
Currently juyterlab-git only displays commit message while the commit description is hidden. Is there any way to enable displaying the description?

**Comment by ianhi** [comment]
Do you mean in the History tab?

Good point, unfortunately I don't think that there currently is a way to do this. Though there likely should be. Two places I could imagine it going are:
1. when you hover the mouse on the short description it shows up in the `title` attribute
2. with a nested caret placed somewhere like this:
![image](https://user-images.githubusercontent.com/10111092/87120434-62db5380-c24e-11ea-8f81-2897237f0f74.png)

**Comment by XiaomoWu** [comment]
Yes I mean in the History tab.

Regarding the place, I think a nested caret would be better. By doing so we could 1) copy & paste the description context; 2) compare multiple expended commit descriptions. Both of them are not achievable with a tooltip.

**Comment by ianhi** [comment]
I'd be good to hear what other people think about that UI. I'm pro the nested caret  because I think that it leads to the most natural place for the description - or perhaps the extra description should always be displayed?

@XiaomoWu If you or anyone else wants to work on this the relevant UI code is here:
https://github.com/jupyterlab/jupyterlab-git/blob/ca8cf3118c08e147b812018edd4e7a9a8ee050ec/src/components/PastCommitNode.tsx#L91-L105

And the backend will also need to be changed a bit to included the extended commit description. Currently it does not get returned from the output of `git log`
https://github.com/jupyterlab/jupyterlab-git/blob/ca8cf3118c08e147b812018edd4e7a9a8ee050ec/jupyterlab_git/git.py#L337-L356

**Comment by XiaomoWu** [comment]
@ianhi Thank you for the reference of code. I'm afraid that I don't have the ability to contribute, but would be glad to see if anyone could do so :P
