### ISSUE TITLE
Visual regressions of the icons in the files list

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#793]
## Icons resize when expanding the panel

![icons_resize](https://user-images.githubusercontent.com/5832902/95147029-73309b00-0777-11eb-9cb9-0028c48c91e7.gif)

Recorded using binder in Firefox 81 on Ubuntu. Same happens in Chrome.
Binder is pinned at JupyterLab 2.2.0

## List is scrollable and needlessly hides elements 

![scrolling](https://user-images.githubusercontent.com/5832902/95147061-87749800-0777-11eb-93ce-aec719bcc347.gif)

Recorded using binder in Firefox 81 on Ubuntu. Same happens in Chrome but the scrollbars are even more annoying.
Binder is pinned at JupyterLab 2.2.0

## Icons are huge and the list is completely unusable when zoomed-in Chrome.

![zoom](https://user-images.githubusercontent.com/5832902/95148232-ba6c5b00-077a-11eb-8be6-1f3e2ce56477.gif)

Chrome 85, Ubuntu; zooming back to the 100% level does not help. Does not happen in Firefox.

**Comment by ianhi** [comment]
Yikes.

I think this is combination of two changes:
**Icon size:** https://github.com/jupyterlab/jupyterlab-git/pull/783
**scrolling:** https://github.com/jupyterlab/jupyterlab-git/pull/792

For the zoomed in icons I think we now take an approach that is closer to what the jlab filebrowser does. We should look at how it avoid size explosion.

**Comment by fcollonval** [comment]
Thanks for reporting @krassowski 

I miss the icon sizing when testing it out :disappointed: - we probably needs to figure out if the icon container flex parameter of JupyterLab are correctly applied:

https://github.com/jupyterlab/jupyterlab/blob/2.2.x/packages/ui-components/src/style/icon.ts#L242-L246

Regarding the empty space in the changed file lists (resulting in the unwanted vertical scroll bar), I saw that since I introduced the virtual list. But I have not been able to figure out a fix. So any help on that front is welcomed.
