### ISSUE TITLE
Enable downloading repository without git metadata 

### ISSUE THREAD

**Issue by adammclaurin** [jupyterlab/jupyterlab-git#856]
For some lesser technical Jupyter users, all they want to do is grab a notebook created by someone else and just run it. The problem is that running a notebook changes the notebook file, which means that the lesser technical person will need to understand how to discard changes in order to obtain an updated notebook from the creator. It would be nice to support a "download" functionality that copies the git repo without the metadata to reduce how much the lesser technical person needs to understand. This is analogous to how the GitHub web interface has a "Clone or download" button.

**Comment by fcollonval** [comment]
Xref: https://github.com/jupyterlab/jupyterlab-git/issues/998

The two issues are trying to address a similar use case. In #998, it goes a bit further by keeping the git link in order to get the notification that the upstream did change.

The main question here is how/where to store a parameter that will tell the extension it is in downloading mode.

**Comment by fcollonval** [comment]
A good solution is the one propose [there](https://stackoverflow.com/questions/11497457/git-clone-without-git-directory); aka

1. Cloning the repository with depth option equals to 1
2. Remove the `.git` repository
