### ISSUE TITLE
jupyterlab_git vs. jupyterlab-git in the README.md

### ISSUE THREAD

**Issue by fortunewalla** [jupyterlab/jupyterlab-git#859]
## Description

I found this extension through the Jupyter web interface and wanted to install it but I have a doubt i.e. In some places of the `README.md` it is mentioned `jupyterlab_git` while in other places it is mentioned `jupyterlab-git`

## Reproduce

or with conda:

`conda install -c conda-forge jupyterlab jupyterlab-git`

....

Uninstall

`pip uninstall jupyterlab_git`

.....

or with conda:

`conda remove jupyterlab-git`

.....

Explicitly enable the server extension by running:

`jupyter server extension enable --py jupyterlab_git`

....

Clone the repo to your local environment

`git clone https://github.com/jupyterlab/jupyterlab-git.git`

....

To execute the tests

`pytest jupyterlab_git`

## Expected behavior

Shouldn't it be just one form, unless I'm missing some detail?

Which form should I use to install it? Thanks

**Comment by fcollonval** [comment]
Hey fortunewalla

Thanks for pointing this out. There are two elements to have in mind when dealing with `-` and `_`. Python does not support `-` in module name. But unfortunately pip replace `_` by `-` in package name. So the package is named `jupyterlab-git` on both [pypi.org](https://pypi.org/project/jupyterlab-git/) and [conda-forge](https://anaconda.org/conda-forge/jupyterlab-git). But the Python package is named `jupyterlab_git`.

Here is the answer for each point you raised:

> `conda install -c conda-forge jupyterlab jupyterlab-git`

This is correct

> Uninstall
> 
> `pip uninstall jupyterlab_git`

This should be correct although it will work due to pip replacing `_` by `-`.
 
> `conda remove jupyterlab-git`

This is correct

> Explicitly enable the server extension by running:
> 
> `jupyter server extension enable --py jupyterlab_git`

This is correct as it tells jupyter server the name of the python package containing the jupyterlab git extension.

_Note_: There is a automatic system to enable server extension when installing the python package. So this should normally not be run by users.

> `git clone https://github.com/jupyterlab/jupyterlab-git.git`

Look at the URL, it contains a `-`. So this is correct.

> To execute the tests
> 
> `pytest jupyterlab_git`

This is correct. It tells pytest to look for tests within the [jupyterlab_git](https://github.com/jupyterlab/jupyterlab-git/tree/master/jupyterlab_git) folder.
