### ISSUE TITLE
Diffing a file throws error

### ISSUE THREAD

**Issue by johannes-AT** [jupyterlab/jupyterlab-git#897]
## Description

Diffing a file throws the following error:

Failed to fetch diff with error:t.iter is not a function

## Reproduce

    Setup a Kubeflow Jupyterlab notebook

    Pull a project

    Change a file

    Switch to gitlab extension in Jupyterlab

    Click on the diff symbol next to the changed file

## Expected behavior

Should open a file showing the differences.

## Context

- Python package version:
# Name                    Version                   Build  Channel
jupyterlab-git            0.30.0b1                 pypi_0    pypi

- Extension version:
JupyterLab v3.0.9
@jupyterlab/git v0.30.0-beta.1 enabled OK (python, jupyterlab-git)

- Git version:
git version 2.25.1

**Comment by fcollonval** [comment]
Hey @johannes-AT 

Could you provide more details on the file diff you are trying to display? File type, status (added, removed, modified,...)?

Could you report the error from the Jupyter server (the terminal logs) and the web browser console error?

**Comment by johannes-AT** [comment]
> Hey @johannes-AT
> 
> Could you provide more details on the file diff you are trying to display? File type, status (added, removed, modified,...)?

Modified a text file (in my case a README.md, reproducable with any text file)

> 
> Could you report the error from the Jupyter server (the terminal logs) and the web browser console error?
Jupyter server error:

Did not find any log entry related to this issue.

Web browser console error:

TypeError: t.iter is not a function
    sr https://www.my-domain.com/.../lab/extensions/@jupyterlab/git/static/703.45ca95c815474f3a9b8c.js:1
    In https://www.my-domain.com/.../lab/extensions/@jupyterlab/git/static/703.45ca95c815474f3a9b8c.js:1
    Ll https://www.my-domain.com/.../lab/extensions/@jupyterlab/git/static/703.45ca95c815474f3a9b8c.js:1
    Ll https://www.my-domain.com/.../lab/extensions/@jupyterlab/git/static/703.45ca95c815474f3a9b8c.js:1
    J https://www.my-domain.com/.../lab/extensions/@jupyterlab/git/static/728.3bdac87c187c279970bb.js:1
    _addDiffViewer https://www.my-domain.com/.../lab/extensions/@jupyterlab/git/static/728.3bdac87c187c279970bb.js:1
    _performDiff https://www.my-domain.com/.../lab/extensions/@jupyterlab/git/static/728.3bdac87c187c279970bb.js:1

**Comment by ValentinB10** [comment]
Hi @johannes-AT, hi @fcollonval,

I just noticed that I had the exact same error but I have to mention that it happens only with diff of Markdown files but no other extensions and it happens only with diffs of changed files but not staged files.

**Comment by fcollonval** [comment]
Thanks for the additional details @ValentinB10 

I successfully reproduce the error in one specific case: New git repository for untracked file staged (markdown or any other type because the file type can't be found).

Otherwise the diff is always showing.

May I ask if that matches what you are seeing? And if not, could you share a markdown file not working?

**Comment by ValentinB10** [comment]
Hey @fcollonval. Here is the behavior I noticed. The issue appears only with Markdown files (but any Markdown file, whatever the content, even with one word).

![titer_issue](https://user-images.githubusercontent.com/58490749/113418460-d406fc00-93c5-11eb-96f0-b4b148c922d2.gif)

In my example, the Markdown file is already tracked, but as you mentioned, when the modified file is staged, the issue is gone.

However, as you may notice in my gif, when this error happens, no other files can be viewed with the editor and I am obliged to reload the jupyterlab interface to make the editor work again. As I installed jupyterlab-git in a collaborative platform, other others are a bit confused by this behaviour.

**Comment by fcollonval** [comment]
> I installed it locally and it works like a charm :)

Glad it solves it as I was not able to reproduce your demo (BTW thank you for taking the time to create a GIF)
